"""PostgreSQL watchlists scans and scanner state

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_table('watchlist_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=180), nullable=True),
    sa.Column('stored_filename', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('validated_count', sa.Integer(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_watchlist_id', sa.Integer(), nullable=True),
    sa.Column('current_snapshot', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scanner_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_interval_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_watchlist_id'], ['watchlist_uploads.id'], ),
    sa.ForeignKeyConstraint(['current_snapshot'], ['watchlist_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forming_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context_10m', sa.String(length=20), nullable=True),
    sa.Column('setup_state', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('distance_status', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['watchlist_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forming_setups_snapshot_id'), 'forming_setups', ['snapshot_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('context_10m', sa.String(length=20), nullable=False),
    sa.Column('context_3m', sa.String(length=20), nullable=False),
    sa.Column('vwap_position', sa.String(length=10), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('ema_5', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_34', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('analysis_3m', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['watchlist_uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_scan_symbol')
    )
    op.create_index(op.f('ix_scan_results_snapshot_id'), 'scan_results', ['snapshot_id'], unique=False)
    op.create_table('sector_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('symbol_count', sa.Integer(), nullable=False),
    sa.Column('bullish_count', sa.Integer(), nullable=False),
    sa.Column('bearish_count', sa.Integer(), nullable=False),
    sa.Column('volatility_metric', sa.Float(), nullable=True),
    sa.Column('relative_strength_metric', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['watchlist_uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'sector', name='uq_snapshot_sector')
    )
    op.create_index(op.f('ix_sector_metrics_snapshot_id'), 'sector_metrics', ['snapshot_id'], unique=False)
    op.create_table('watchlist_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_upload_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_upload_id'], ['watchlist_uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_upload_id', 'symbol', name='uq_watchlist_symbol')
    )
    op.create_index(op.f('ix_watchlist_symbols_watchlist_upload_id'), 'watchlist_symbols', ['watchlist_upload_id'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(sa.table('app_state', sa.column('id', sa.Integer),
                            sa.column('status', sa.String), sa.column('scan_interval_seconds', sa.Integer)),
                   [{'id': 1, 'status': 'waiting', 'scan_interval_seconds': 60}])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbols_watchlist_upload_id'), table_name='watchlist_symbols')
    op.drop_table('watchlist_symbols')
    op.drop_index(op.f('ix_sector_metrics_snapshot_id'), table_name='sector_metrics')
    op.drop_table('sector_metrics')
    op.drop_index(op.f('ix_scan_results_snapshot_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_forming_setups_snapshot_id'), table_name='forming_setups')
    op.drop_table('forming_setups')
    op.drop_table('app_state')
    op.drop_table('watchlist_uploads')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
